#!/bin/bash

SOURCE_DIR="/home/user/Documents"
BACKUP_DIR="/home/user/backups"
TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
BACKUP_NAME="backup_$TIMESTAMP.tar.gz"

mkdir -p "$BACKUP_DIR"

echo "[$TIMESTAMP] Starting backup of $SOURCE_DIR..."

tar -czf "$BACKUP_DIR/$BACKUP_NAME" -C "$SOURCE_DIR"

if [$? -eq 0 ]; then
  echo "[$TIMESTAMP] Success: Backup saved to $BACKUP_DIR/$BACKUP_NAME"
else
  echo "[$TIMESTAMP] Error: Backup failed!" >&2
  exit 1
fi

# This will delete backups that are older than 7 days. This is to save space
find "$BACKUP_DIR" -type f -name "backup_*.tar.gz" -mtime +7 -delete 


